Use the fully qualified name `window.location.host` and not just `location.host`
I was trying some things with jest and babel, and I encountered the following error when trying to compile the frontend code

```
ReferenceError: location is not defined
```

The Dashboard code is not suffering from this, because
1. `location` is defined as a global in the actual browsers
2. the Jest config defines `testEnvironment: 'jest-environment-jsdom',` and that (somehow) instructs babel to assume browser env

I want to compile without defining `testEnvironment`, and since there is no harm in referencing `location` though `window`, why not just do it that way?