[E2E] Fix after() hooks for skipped tests to avoid unnecessary teardown (#4323)
* Prevent after() hooks for skipped tests to avoid unnecessary teardown

When running Cypress tests with grepTags that don't match any test tags,
the tests are skipped but their after() hooks are still executed.
This causes unnecessary teardown operations and false test failures.

For example, running:
  cypress:run -- --env 'grepTags=@BlaBla' -s '**/distributedWorkloadMetrics/**/*.ts'

Will skip the tests but still execute their after() hooks,
leading to errors like:
  TypeError: Cannot read properties of undefined (reading 'localQueue')

This change fixes the the unnecessary teardown of excluded tests.

In addition, fix type checking in clusterSettingsUtils.ts.
It is required to fix testAdminClusterSettings.cy failure in ODH (only):
`TypeError: Cannot read properties of undefined`

Signed-off-by: manosnoam <nmanos@redhat.com>

* Fix E2E RHOAIENG-26330: Admin should access Cluster Settings

Signed-off-by: manosnoam <nmanos@redhat.com>

* Fix After hooks in userManagement tests

Signed-off-by: manosnoam <nmanos@redhat.com>

---------

Signed-off-by: manosnoam <nmanos@redhat.com>