fix: Correct argument order in mockGetPipelineVersions call
The mockGetPipelineVersions signature is:
mockGetPipelineVersions(namespace, versions, pipelineId)

But it was being called with arguments in wrong order:
mockGetPipelineVersions([], mockPipeline.pipeline_id, projectName)

This caused TypeScript error:
error TS2345: Argument of type 'never[]' is not assignable to parameter of type 'string'

Fixed by reordering to:
mockGetPipelineVersions(projectName, [], mockPipeline.pipeline_id)